### ISSUE TITLE
CreateOrderRequestLineItem - Quantity Property remains null

### ISSUE THREAD

**Issue by mmcc1** [square/connect-csharp-sdk#125]
One or more errors occurred. (Quantity is a required property for CreateOrderRequestLineItem and cannot be null): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Square.Connect.Model.CreateOrderRequestLineItem..ctor(String Name, String Quantity, Money BasePriceMoney, String VariationName, String Note, String CatalogObjectId, List`1 Modifiers, List`1 Taxes, List`1 Discounts)
at CBAOrderCreate.Function.FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context) in C:\Clients\Comeback Cash\Code\CBAOrderCreate\CBAOrderCreate\Function.cs:line 232

**Comment by mmcc1** [comment]
I tested this with the latest release and it is still an issue.
